### PR TITLE
New tutorial and GUI parcel functionality

### PR DESCRIPTION
**Pull request by wblumberg**
This pull request includes a wealth of new things I've been working on for a while.

## Scripting Tutorial

I've included a tutorial folder within the main SHARPpy directory for others to use.  It includes a sample data file from the Pilger, NE 2014 tornado for the user to work with.  The tutorial is within the IPython notebook that is included.  It teaches the user about reading in the data, constructing the profile object, drawing parcel traces, computing convection indices, and plotting the data in Matplotlib.

## New GUI Parcel Functions

- Ability to change the parcel trace being displayed on the Skew-T by clicking on a parcel name in the Thermodynamics inset.
- Thermodynamics inset now highlights the parcel being displayed in the Skew-T.
- The parcel highlighted in the Thermodynamics window has also changes the colors of the text based upon how favorable the numbers are for convection.
- Changing the parcel in the thermodynamics inset will also modify the storm slinky window.
- Double clicking on the thermodynamic inset will open up a window that can be used to modify which parcels are displayed in the thermodynamic inset.  The type of parcels that are displayed are saved in the configuration file setup by Tim Supinie.
- A user defined parcel and effective inflow parcel are now included in the ConvectiveProfile class.  I figured that since params.parcelx() is so fast, it wouldn't matter much if I added it into the set of computations.
- The user defined parcel can be set by right clicking on the Skew-T and selecting which parcel you wish to lift.  Four options are available: This Level, 50 mb layer, 100 mb layer, Custom Parcel (custom means custom layer).  When lifting a layer, the location of the cursor corresponds to the bottom of the layer.

screen shot 2015-03-18 at 2 33 24 pm

### CODE REVIEW

**Comment by keltonhalbert** [comment]
Going to give it a try right now!

**Comment by keltonhalbert** [comment]
First things first...

It looks like your code is using the old setup scripts. To be safe, call you do a pull on the upstream change Patrick made regarding the setup.py script?

**Comment by wblumberg** [comment]
Hmm.  I could have sworn I did that.  Let me double check.  Also, resetting the hodograph craps out.  I know why.

**Comment by wblumberg** [comment]
It says everything is up to date...

I did git fetch upstream and git pull upstream master

**Comment by keltonhalbert** [comment]
Correction: It was bad on my end. You're fine.

**Comment by keltonhalbert** [comment]
Everything looks great! Just a few minor bugs I caught...

1) When you change the parcel by double-clicking the thermo window (say, remove EFF and add FCST) and the increment or decrement by a time step, the thermo window will reset it back to the default display. Ideally, if you change a displayed parcel, it should stick throughout time. 

2) When selecting the USER parcel in the thermo window, if I set a new custom parcel (from lift this parcel in the SkewT window), it resets the parcels to the default display. Ideally this should not reset the parcels in the Thermo window. 

If we can get those two bugs taken care of, I don't see anything else preventing this from being merged. It looks and feels outstanding! Great work!

**Comment by keltonhalbert** [comment]
Also: I stuck the IPython notebook in the notebook viewer - looks outstanding! I think this will be very helpful for users getting started. I've needed something like this on several occasions that I've tried to help some people use SHARPpy on their datasets.

**Comment by wblumberg** [comment]
Thanks!  My contributes have been lurking in the shadows...

Dang.  I thought I had fixed those bugs.  Let me see what I can do about that.

**Comment by keltonhalbert** [comment]
Another thing I have noticed: upon creating the window, the thermo window defaults to selecting the effective parcel, but the mupcl is the one default displayed in the SkewT window. I would recommend making the default selected parcel in the thermo window be the mupcl.

**Comment by wblumberg** [comment]
Okay.  i think those first two bugs are fixed.  Now onto forcing the MU parcel to be a default.

**Comment by wblumberg** [comment]
Okay.  It will default to the MU parcel if it's available and upon initialization of the thermodynamic inset.  Otherwise, it will not default to the MU parcel (i.e. if you're looping).

**Comment by keltonhalbert** [comment]
Sweet. When I get back from dinner, I'll test it and then we should be able to go ahead and merge the pull request.

**Comment by keltonhalbert** [comment]
Changes look good. One more thing (and this may not be a bug),
but when you define a custom parcel and lift it for a given time, when you increment the time step, should the next time step lift a parcel from the same level, or be blank? Currently, if you choose a user defined parcel and advance the time step, the USER parcel becomes empty again. I just want to clarify how it is supposed to behave before merging. 

pcl2
pcl1

**Comment by wblumberg** [comment]
Nope.  Not a bug.  There might be a way to propagate the parcel values over time, but I don't think it's a necessary function at this time.

**Comment by keltonhalbert** [comment]
Awesome. Merging.

**Comment by wblumberg** [comment]
Hurray!

**Pull request merged**
