### PR TITLE
added the NUCAPS data source to the display

### PR DESCRIPTION
**Pull request by Jeff-Szkodzinski**
I've added functionality to display NUCAPS sounding profiles for NOAA-20, Suomi-NPP, Metop-A, B & C.  Modifications were made to full_gui.py to deactivate the model cycle times for observational data and improve the look and feel of the main gui.  Also coded a section in map.py to change the color of the dots based on the QC flag of the satellite footprint.  Let me know what you think of these changes.

### CODE REVIEW

**Comment by wblumberg** [comment]
Hi Jeff!

Okay!  Glad you were able to get this successfully started!  I see a few things so far:

1) Let's do a pull request to a branch other than master.  We try not to to do pull requests into master for feature additions without more testing (bug fixes are different) since it's the stable release.  Could you please submit it to a nucaps_test branch instead?  That way we can do those incremental changes to the code base and have a branch @tsupinie and I can review.  You can point your testers to that branch if you'd like.
2.) The checks failed (ignoring the Appveyor one) on creation of the SPCWindow, so there's some bug catching you'll need to do.  You can see the errors here: https://travis-ci.org/github/sharppy/SHARPpy/jobs/734328327.  I also was able to reproduce them using your code by trying to load one of the soundings from the other data sources (Observed, NAM, etc.).  
3.) I think we should wait till you have the .csv or .xml files to the NUCAPS data, as right now we don't have a good way to independently test what you've added here.  

Thanks for the submission! :)

Greg

**Comment by Jeff-Szkodzinski** [comment]
Hi Greg,

 

I made some fixes to my nucaps_test Git branch, so the issue with the SPC window not launching has been resolved.  I’m about to submit a new pull request but I wasn’t sure how to submit my changes to a new “nucaps_test” branch in your base repository.  I’m only seeing options for submitting it to master along with other branches that have been previously created by other users.  

 

The remote text files and CSVs for NOAA-20 and S-NPP are being generated in real-time on an https site hosted by NASA SPoRT.  You’ll notice in standard.xml that the remote paths have been given, so you should be able to test how the data loads and displays all in one go.  I like the idea of having our beta testers test out the program from nucaps_test since we’ll likely be applying small, incremental enhancements as we go and will see how those work out.

 

Thanks,

Jeff

**Comment by wblumberg** [comment]
Hi @Jeff-Szkodzinski !

I've had a lot going on over the last week or so, so I haven't been able to respond to your emails and these changes yet.  Regardless, I've made a new branch on the SHARPpy project called nucaps-test that you can change your pull request submission to.  We can then do some tests then.  I don't know about the binaries yet - the binary generation doesn't seem to be working since something happened with the Azure DevOps CI part that I need to troubleshoot.

Thanks!

Greg

**Comment by Jeff-Szkodzinski** [comment]
Hi Greg,

No worries.  I pointed the base branch to 'nucaps_test' so you should now be able to see the new changes.

Thanks!

Jeff

**Pull request merged**
