### PR TITLE
Cleanup for the release

### PR DESCRIPTION
**Pull request by tsupinie**

### CODE REVIEW

**Comment by wblumberg** [comment]
Do you have any pictures of the Windows changes?

**Comment by tsupinie** [comment]
Yes, I posted them on the thread for the Windows GUI issues.

**Comment by wblumberg** [comment]
Yeah the different text sizes was a result of the porting from SHARP.  SHARP had the different sizes, so I chose to duplicate it.  

The new images look sick, by the way.  It really changes the quality of the program on Windows.  Two things I noticed on the images:

1.) Think you can shift the "Storm Slinky" text box up a little bit on the Windows version?  That part probably shouldn't be too hard.

2.) The SRWIND and BRN Shear looks good, but the Corfidi/Bunkers section looks like it still has some alignment issues.

**Comment by tsupinie** [comment]
Check my latest commit.  Images on the Windows GUI issues thread again.

**Comment by wblumberg** [comment]
Okay.  I just made some changes to the params.py file and added the 0-3 MLCAPE to the thermo window.  Trying to push.  Accidentally made these changes to my master branch.

**Comment by wblumberg** [comment]
It did look fine when I looked at it by the way.

**Comment by tsupinie** [comment]
You have a missing parenthesis on line 2759 of params.py.  I'd fix it myself, but I'm not entirely sure where the missing parenthesis is supposed to go.

**Comment by wblumberg** [comment]
Yeah.  Just fixed it.  I think my fork is messed up, so I'm just uploading it straight to the main repository for now.

**Comment by tsupinie** [comment]
Also, I'm not sure the 0-3 km CAPE routine is working properly.  The sounding from the Washington, IL tornado should have some 0-3 km MLCAPE, but it's showing up as 0.  BTW, it also seems to affect the ESP variable.

image

**Comment by wblumberg** [comment]
Hmmm.  Interesting.  Does SPC have the 3CAPE?  Yeah, ESP includes the 0-3 MLCAPE.  This is quite surprising as this function has worked in the past...

**Pull request merged**
